### ISSUE TITLE
Remove reference to BlueXP System Manager

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/bluexp-volume-caching#10]
### Page URL

https://docs.netapp.com/us-en/bluexp-volume-caching/use/cache-manage.html

### Page title

Manage a cache

### Summary

Please change the reference to "BlueXP System Manager" which is not the right terminology.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Thx, @netapp-bcammett. Will update the text.

**Comment by amgrissino** [comment]
Pushing changes out now
