### ISSUE TITLE
internal links are tagged as external 

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/bluexp-volume-caching#5]
### Page URL

https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-quick-start.html

### Page title

Quick start for BlueXP volume caching

### Summary

The links on this page are all internal to this site but are tagged as external links.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-quick-start.html - changed to internal links
https://docs.netapp.com/us-en/bluexp-volume-caching/get-started/cache-login.html - keeping as is because 2 links go to another  GitHub repo.
